[package]
name = "openweathermap_client"
description = "A client for querying the weather from the free OpenWeatherMap API."
version = "0.1.0"
edition = "2021"
authors = ["evaneaston"]
homepage = "https://github.com/evaneaston/openweathermap"
repository = "https://github.com/evaneaston/openweathermap"
license = "MIT-0"
keywords = ["openweathermap", "prometheus", "metrics", "exporter"]
categories = ["api-bindings"]

[dependencies]
hyper = { version = "0.14.20", features = ["client", "runtime", "http1","http2"] }
hyper-tls = "0.5.0"
http = "0.2"
log = "0.4"
serde = { version = "1.0.143", features = ["derive"] }
serde_yaml = "0.9.9"
thiserror = "1.0.37"
url = "2.3.1"
